# Generated by Django 6.0 on 2026-01-21 13:10

import django.core.validators
import imagekit.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indabax', '0002_learningresource'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('image', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='indabax/hero/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'webp'])])),
                ('is_active', models.BooleanField(default=False, help_text='Only one hero can be active.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hero Section',
                'verbose_name_plural': 'Hero Sections',
            },
        ),
        migrations.CreateModel(
            name='Leader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('profile_image', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='indabax/leaders/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'webp'])])),
                ('bio', models.TextField(blank=True)),
                ('course', models.CharField(blank=True, max_length=100)),
                ('year', models.PositiveIntegerField()),
                ('is_current', models.BooleanField(default=False, help_text='Mark as current leader.')),
                ('linkedin', models.URLField(blank=True)),
                ('twitter', models.URLField(blank=True)),
                ('github', models.URLField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Leader',
                'verbose_name_plural': 'Leaders',
                'ordering': ['-is_current', '-year', 'name'],
            },
        ),
        migrations.AlterModelOptions(
            name='learningresource',
            options={'ordering': ['-date_added'], 'verbose_name': 'Learning Resource', 'verbose_name_plural': 'Learning Resources'},
        ),
        migrations.AlterField(
            model_name='learningresource',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
