# Generated by Django 6.0 on 2026-01-23 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indabax', '0003_herosection_leader_alter_learningresource_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningresource',
            name='image',
            field=models.ImageField(blank=True, help_text='Optional thumbnail/preview image', null=True, upload_to='indabax/resources/images/'),
        ),
    ]
