# Generated by Django 6.0 on 2026-01-23 11:08

import imagekit.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indabax', '0004_learningresource_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='indabaxsettings',
            name='mission_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='indabaxsettings',
            name='mission_title',
            field=models.CharField(blank=True, default='Our Mission', max_length=200),
        ),
        migrations.AddField(
            model_name='indabaxsettings',
            name='vision_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='indabaxsettings',
            name='vision_mission_image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, help_text='Optional image for Vision & Mission section', null=True, upload_to='indabax/vision_mission/'),
        ),
        migrations.AddField(
            model_name='indabaxsettings',
            name='vision_title',
            field=models.CharField(blank=True, default='Our Vision', max_length=200),
        ),
    ]
