# Generated by Django 6.0 on 2026-01-23 11:49

import imagekit.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indabax', '0005_indabaxsettings_mission_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningresource',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, help_text='Optional thumbnail/preview image', null=True, upload_to='indabax/resources/images/'),
        ),
    ]
